// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA97RCnnuPtZb20QBhPPXgP7e9I3hNr5ME',
    appId: '1:109664242814:web:55e14d443cf7d2ec055c2f',
    messagingSenderId: '109664242814',
    projectId: 'fastfood-inteligente',
    authDomain: 'fastfood-inteligente.firebaseapp.com',
    storageBucket: 'fastfood-inteligente.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiocKBP6IVt_n-DLMOtD2QvFy7H-MJfQY',
    appId: '1:109664242814:android:db37fa7df49e2f03055c2f',
    messagingSenderId: '109664242814',
    projectId: 'fastfood-inteligente',
    storageBucket: 'fastfood-inteligente.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6TLf7P_g7I9lEE8Gu5-xNZjJ8L6_gHXs',
    appId: '1:109664242814:ios:8b07714fc440f4e0055c2f',
    messagingSenderId: '109664242814',
    projectId: 'fastfood-inteligente',
    storageBucket: 'fastfood-inteligente.appspot.com',
    iosClientId: '109664242814-2s0gpk930bc8vkb7s160ctvjbg5d9bk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastfoodInteligenteFlutter',
  );
}
