// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhVgqpvF5GDylw-lDg4GyOUekXTSN-fVY',
    appId: '1:518388818633:web:f90b2af1090869e25ca318',
    messagingSenderId: '518388818633',
    projectId: 'hamburgueria-inteligente-459e7',
    authDomain: 'hamburgueria-inteligente-459e7.firebaseapp.com',
    storageBucket: 'hamburgueria-inteligente-459e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaMDp3opKT4RpeDUaMjaJGcOdw8Bo_nF8',
    appId: '1:518388818633:android:09aaaf3f6e83aa0b5ca318',
    messagingSenderId: '518388818633',
    projectId: 'hamburgueria-inteligente-459e7',
    storageBucket: 'hamburgueria-inteligente-459e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtVgNYhHeZBMgvXEypT3UGPpC1rBGUH5M',
    appId: '1:518388818633:ios:6839a532b87cd46d5ca318',
    messagingSenderId: '518388818633',
    projectId: 'hamburgueria-inteligente-459e7',
    storageBucket: 'hamburgueria-inteligente-459e7.appspot.com',
    iosClientId: '518388818633-uv9obrrbgfq8lh8lps1seq9fac7qcfik.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastfoodInteligenteFlutter',
  );
}
