// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3-4B4GYRpBQDUI1OFIjKRf8cagnz7Zq8',
    appId: '1:673974094468:web:e7640bbf7efa7fc49210d1',
    messagingSenderId: '673974094468',
    projectId: 'maisumatela',
    authDomain: 'maisumatela.firebaseapp.com',
    storageBucket: 'maisumatela.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBoCXH7oKpYq0UBXAiGXnkCklc1k-LUkU',
    appId: '1:673974094468:android:4a996bad5ef5ffd49210d1',
    messagingSenderId: '673974094468',
    projectId: 'maisumatela',
    storageBucket: 'maisumatela.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa2ZLcQaqdeubVzNHuEwpnMABco7od9I8',
    appId: '1:673974094468:ios:4d5e8f8bf641e55a9210d1',
    messagingSenderId: '673974094468',
    projectId: 'maisumatela',
    storageBucket: 'maisumatela.appspot.com',
    iosClientId: '673974094468-l3gr8d79irqjp0vqr6467njfcb16c1ka.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastfoodInteligenteFlutter',
  );
}
